### ISSUE TITLE
Companion Module Crashed During Event During VideoOff Update

### ISSUE THREAD

**Issue by digitaldrummerj** [bitfocus/companion-module-zoom-osc-iso#90]
I was running an event and was not doing anything at the time but noticed when I went to click on a button that nothing happened and looking at the connections it said "unknown stopped" for the status of the ZoomOSC connection.  I then saw these messages in the logs.

ZoomOSC 4.2.0 PRO
Companion v3.0.0+5870-beta-bb541a1a
Windows 10 is running Companion
Windows 11 is running ZoomOSC

I am using the included ZoomOSC module of Companion.

There are 257 people on Zoom for this event.

```
info: changing config!
info: Listening to ZoomOSC on port: 1234
debug: wrong arguments in OSC feedback
info: receiving:{"address":"/zoomosc/user/chat","args":[{"type":"i","value":-1},{"type":"s","value":"Betty Powell (she/her)"},{"type":"i","value":20},{"type":"i","value":16915456},{"type":"s","value":"#EveryWinCounts"}]}
debug: wrong arguments in OSC feedback
info: receiving:{"address":"/zoomosc/user/chat","args":[{"type":"i","value":-1},{"type":"s","value":"Vivian Adorsu"},{"type":"i","value":-1},{"type":"i","value":50380800},{"type":"s","value":"#MoneyLoveSpeed"}]}
error: Feedback check failed: {"id":"COcK2avcdR2Qpyh0QX765","controlId":"bank:80-2","feedbackId":"index_Based","options":{"position":1,"type":1},"disabled":false,"image":{"width":72,"height":58},"page":80,"bank":2,"referencedVariables":null} - Cannot read properties of undefined (reading 'mute') TypeError: Cannot read properties of undefined (reading 'mute')
    at Object.callback (C:\Work\repos\companion-module-dev\companion-module-zoom-osc-iso\dist\feedback.js:163:66)
    at C:\Work\repos\companion-module-dev\companion-module-zoom-osc-iso\node_modules\@companion-module\base\dist\internal\feedback.js:208:40
Feedback check failed: {"id":"YTASrduG-p1HqGeZUJ-2k","controlId":"bank:80-2","feedbackId":"index_Based","options":{"position":1,"type":2,"handRaised":1},"disabled":false,"image":{"width":72,"height":58},"page":80,"bank":2,"referencedVariables":null} - Cannot read properties of undefined (reading 'handRaised') TypeError: Cannot read properties of undefined (reading 'handRaised')
    at Object.callback (C:\Work\repos\companion-module-dev\companion-module-zoom-osc-iso\dist\feedback.js:167:66)
    at C:\Work\repos\companion-module-dev\companion-module-zoom-osc-iso\node_modules\@companion-module\base\dist\internal\feedback.js:208:40
Feedback check failed: {"id":"sBNcF9uVxaSLbMpbvSCPS","controlId":"bank:80-2","feedbackId":"index_Based","options":{"position":1,"type":4},"disabled":false,"image":{"width":72,"height":58},"page":80,"bank":2,"referencedVariables":null} - Cannot read properties of undefined (reading 'userName') TypeError: Cannot read properties of undefined (reading 'userName')
    at Object.callback (C:\Work\repos\companion-module-dev\companion-module-zoom-osc-iso\dist\feedback.js:169:111)
    at C:\Work\repos\companion-module-dev\companion-module-zoom-osc-iso\node_modules\@companion-module\base\dist\internal\feedback.js:208:40
Feedback check failed: {"id":"hRfyLHreT4S-rkNsH0a2V","controlId":"bank:80-3","feedbackId":"index_Based","options":{"position":2,"type":1},"disabled":false,"image":{"width":72,"height":58},"page":80,"bank":3,"referencedVariables":null} - Cannot read properties of undefined (reading 'mute') TypeError: Cannot read properties of undefined (reading 'mute')
    at Object.callback (C:\Work\repos\companion-module-dev\companion-module-zoom-osc-iso\dist\feedback.js:163:66)
    at C:\Work\repos\companion-module-dev\companion-module-zoom-osc-iso\node_modules\@companion-module\base\dist\internal\feedback.js:208:40
Feedback check failed: {"id":"BT9L4ngAfs1N0M6OTiPIk","controlId":"bank:80-3","feedbackId":"index_Based","options":{"position":2,"type":2,"handRaised":1},"disabled":false,"image":{"width":72,"height":58},"page":80,"bank":3,"referencedVariables":null} - Cannot read properties of undefined (reading 'handRaised') TypeError: Cannot read properties of undefined (reading 'handRaised')
    at Object.callback (C:\Work\repos\companion-module-dev\companion-module-zoom-osc-iso\dist\feedback.js:167:66)
    at C:\Work\repos\companion-module-dev\companion-module-zoom-osc-iso\node_modules\@companion-module\base\dist\internal\feedback.js:208:40
Feedback check failed: {"id":"GJRCpPTLcH8azaMRgF9bb","controlId":"bank:80-3","feedbackId":"index_Based","options":{"position":2,"type":4},"disabled":false,"image":{"width":72,"height":58},"page":80,"bank":3,"referencedVariables":null} - Cannot read properties of undefined (reading 'userName') TypeError: Cannot read properties of undefined (reading 'userName')
    at Object.callback (C:\Work\repos\companion-module-dev\companion-module-zoom-osc-iso\dist\feedback.js:169:111)
    at C:\Work\repos\companion-module-dev\companion-module-zoom-osc-iso\node_modules\@companion-module\base\dist\internal\feedback.js:208:40
debug: ZOSC_4.2.0_WIN Pro
debug: KCF Live, user role 2
```

Another error
```
debug: Removed:[{"zoomId":50477056,"userName":"Michael  Steinberg"}]
error: C:\Work\repos\companion-module-dev\companion-module-zoom-osc-iso\dist\osc.js:222
                            this.instance.ZoomUserData[zoomId].videoOn = false;
                                                                       ^

TypeError: Cannot set properties of undefined (setting 'videoOn')
    at OSC.processData (C:\Work\repos\companion-module-dev\companion-module-zoom-osc-iso\dist\osc.js:222:72)
    at osc.UDPPort.<anonymous> (C:\Work\repos\companion-module-dev\companion-module-zoom-osc-iso\dist\osc.js:71:18)
    at osc.UDPPort.emit (node:events:513:28)
    at osc.UDPPort.emit (node:domain:489:12)
    at osc.firePacketEvents (C:\Work\repos\companion-module-dev\companion-module-zoom-osc-iso\node_modules\osc\src\osc-transports.js:25:18)
    at p.decodeOSC (C:\Work\repos\companion-module-dev\companion-module-zoom-osc-iso\node_modules\osc\src\osc-transports.js:85:17)
    at osc.UDPPort.emit (node:events:513:28)
    at osc.UDPPort.emit (node:domain:489:12)
    at Socket.<anonymous> (C:\Work\repos\companion-module-dev\companion-module-zoom-osc-iso\node_modules\osc\src\platforms\osc-node.js:102:18)
    at Socket.emit (node:events:513:28)

Node.js v18.14.2
```

Here is some debugging info.  Looks like the issue is that the user is leaving the Zoom and the videooff is trying to modify that user but they no longer exist in the user data.  

```
debug: Removed:[{"zoomId":50591744,"userName":"Zoom User Name."}]
info: receiving:{"address":"/zoomosc/user/videoOff","args":[{"type":"i","value":-1},{"type":"s","value":"Zoom User Name"},{"type":"i","value":-1},{"type":"i","value":50591744}]}
debug: videoOff: zoomUserData[50591744] - undefined
```

I added the following debug statement to the osc videooff 

```
this.instance.log(
  'debug',
  `videoOff: zoomUserData[${zoomId}] - ${JSON.stringify(this.instance.ZoomUserData[zoomId])}`
)
```

**Comment by digitaldrummerj** [comment]
Also, saw the issue with group feedback this morning.  I will work on adding that into the PR

**Comment by digitaldrummerj** [comment]
added checks to group feedback in PR
